version: "3"

services:

  ldap:
    build: ./ldap
    image: custom/ldap
    container_name: custom_ldap
    restart: always
    environment:
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - LDAP_ORGANISATION=${LDAP_ORGANISATION}
      - LDAP_DOMAIN=${LDAP_DOMAIN}
    healthcheck:
      test: ["CMD-SHELL", "/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - frontend

  ldapadmin:
    image: osixia/phpldapadmin
    container_name: custom_ldapadmin
    restart: always
    environment:
    - PHPLDAPADMIN_LDAP_HOSTS=ldap
    ports:
    - 5543:443
    networks:
    - frontend

  nifi:
    build: ./nifi
    image: custom/nifi
    container_name: custom_nifi
    restart: always
    ports:
      - 5443:8443
    environment:
      - AUTH=ldap
      - KEYSTORE_PATH=/opt/secrets/keystore.jks
      - KEYSTORE_TYPE=JKS
      - KEYSTORE_PASSWORD=monsoon
      - TRUSTSTORE_PATH=/opt/secrets/truststore.jks
      - TRUSTSTORE_PASSWORD=monsoon
      - TRUSTSTORE_TYPE=JKS
      - INITIAL_ADMIN_IDENTITY=${NIFI_INITIAL_ADMIN_IDENTITY}
      - LDAP_AUTHENTICATION_STRATEGY=SIMPLE
      - LDAP_MANAGER_DN=${NIFI_LDAP_MANAGER_DN}
      - LDAP_MANAGER_PASSWORD=${NIFI_LDAP_MANAGER_PASSWORD}
      - LDAP_USER_SEARCH_BASE=${NIFI_LDAP_USER_SEARCH_BASE}
      - LDAP_USER_SEARCH_FILTER=uid={0}
      - LDAP_IDENTITY_STRATEGY=USE_DN
      - LDAP_URL=ldap://ldap:389
      - NIFI_WEB_PROXY_HOST=ucc-ipc-0:5443
      - NIFI_WEB_HTTP_HOST=ucc-ipc-0
      - NIFI_REMOTE_INPUT_HOST=ucc-ipc-0
    networks:
      - frontend
 
networks:
  frontend:
