version: "3"

services:

  portainer:
    image: portainer/portainer
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_volume:/data
    networks:
      - frontend

  ldap:
    image: monsoon/ldap:0.0.1
    container_name: monsoon_ldap
    restart: always
    ports:
      - 389:389
    environment:
      - LDAP_ADMIN_PASSWORD=monsoon
      - LDAP_ORGANISATION=Monsoon consortium
      - LDAP_DOMAIN=monsoon.eu
    healthcheck:
      test: ["CMD-SHELL", "/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ldap_volume:/var/lib/ldap
      - ldap_conf_volume:/etc/ldap/slapd.d
    networks:
      - frontend

  ldapadmin:
    image: osixia/phpldapadmin
    container_name: monsoon_ldapadmin
    restart: always
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap
    ports:
      - 9443:443
    networks:
      - frontend

  nifi:
    image: monsoon/nifi:0.0.1
    container_name: monsoon_nifi
    restart: always
    ports:
      - 8443:8443
    environment:
      - AUTH=ldap
      - KEYSTORE_PATH=/opt/secrets/keystore.jks
      - KEYSTORE_TYPE=JKS
      - KEYSTORE_PASSWORD=monsoon
      - TRUSTSTORE_PATH=/opt/secrets/truststore.jks
      - TRUSTSTORE_PASSWORD=monsoon
      - TRUSTSTORE_TYPE=JKS
      - INITIAL_ADMIN_IDENTITY=uid=admin,ou=people,dc=monsoon,dc=eu
      - LDAP_AUTHENTICATION_STRATEGY=SIMPLE
      - LDAP_MANAGER_DN=cn=admin,dc=monsoon,dc=eu
      - LDAP_MANAGER_PASSWORD=monsoon
      - LDAP_USER_SEARCH_BASE=ou=people,dc=monsoon,dc=eu
      - LDAP_USER_SEARCH_FILTER=uid={0}
      - LDAP_IDENTITY_STRATEGY=USE_DN
      - LDAP_URL=ldap://ldap:389
      - NIFI_WEB_PROXY_HOST=ucc-ipc-0:8443
      - NIFI_WEB_HTTP_HOST=ucc-ipc-0
      - NIFI_REMOTE_INPUT_HOST=ucc-ipc-0
    volumes:
      - ./nifi/secrets:/opt/secrets
      - ./data:/data
      - ./nifi/conf/templates:/opt/nifi/nifi-1.6.0/conf/templates
      - nifi_conf_volume:/opt/nifi/nifi-1.6.0/conf
      - nifi_logs_volume:/opt/nifi/nifi-1.6.0/logs
      - nifi_database_volume:/opt/nifi/nifi-1.6.0/database_repository
      - nifi_flowfile_volume:/opt/nifi/nifi-1.6.0/flowfile_repository
      - nifi_content_volume:/opt/nifi/nifi-1.6.0/content_repository
      - nifi_provenance_volume:/opt/nifi/nifi-1.6.0/provenance_repository
    networks:
      - frontend

volumes:
  portainer_volume:
    driver: local
  ldap_volume:
    driver: local
  ldap_conf_volume:
  nifi_conf_volume:
    driver: local
  nifi_logs_volume:
    driver: local
  nifi_database_volume:
    driver: local
  nifi_flowfile_volume:
    driver: local
  nifi_content_volume:
    driver: local
  nifi_provenance_volume:
    driver: local
 
networks:
  frontend:
